# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c2c39e4192017e6a2064dc9bc70fc95ce73f3e9ec61ee4649943deb1215862f52d98cb00a3aa396945cfd3addda2ee50bc826b163e256be08265fc9ff7c3498

test:
  secret_key_base: 17e998c335ab43e4e9d7faa5046562150e1bac6f7df1fd65a89bbc74fcdb9c0c64b4506adf3621875099843c30f0c7e107739aa977390e5c01780567a0bcc519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
